### ISSUE TITLE
[FIX] Streamlit 에서 typical 이미지 OCR이 바로 실행되지 않는 버그 고치기

### ISSUE THREAD

**Issue by Yera10** [boostcampaitech4lv23cv2/final-project-level2-cv-11#41]
# Bug Describe
 - Frontend 실행 시, typical 이미지를 업로드하면, 바로 OCR이 수행된 결과가 뜨지 않는 경우가 있음. 

# Expected behavior
 - [ ] 버그 발생 원인 찾기

**Comment by ganghe74** [comment]
Streamlit 사용 안함
